### ISSUE TITLE
NDA for contrastive learning

### ISSUE THREAD

**Issue by YAaNnGg** [ermongroup/NDA#1]
Hi, thanks for sharing your inspiring work. 

I am a little bit confused about how to get the feature of the NDA sample. It's not clear in the paper. Should it be passed through encoder_q or encoder_k, with grad or without grad?  Could you please specify this part?

Thanks a lot!

**Comment by a7b23** [comment]
Hi, once the network is trained, to get the sample you can just pass the image through encoder_q. It wouldn't matter if you do it with grad or without grad. Doing without grad would help you save on the memory.

**Comment by YAaNnGg** [comment]
Thanks for your reply.  Sorry, I don't express my problem clearly before.  In fact, I wanted to know how do you get the feature in the training stage for contrastive loss.  And in this situation, I think the grad matters, and maybe the encoder matters too. 
(I didn't find the related code in this repo or others, but I am not sure. Let me know if it has already existed. Thanks again)
